default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  host: <%= ENV.fetch("PGHOST", "db") %>
  port: <%= ENV.fetch("PGPORT", 5432) %>
  username: <%= ENV.fetch("PGUSER", "postgres") %>
  password: <%= ENV["PGPASSWORD"] %>

development:
  <<: *default
  database: <%= ENV.fetch("PGDATABASE", "amply_development") %>

test:
  <<: *default
  database: <%= ENV.fetch("PGDATABASE", "amply_test") %>

production:
  primary:
    <<: *default
    database: <%= ENV.fetch("PGDATABASE", "amply_production") %>

  cable:
    <<: *default
    database: <%= ENV.fetch("PGDATABASE", "amply_production") %>
